version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: github-agent-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_agent
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  discord-bot:
    build: apps/discord-bot
    environment:
      - DISCORD_BOT_ID=${DISCORD_BOT_ID}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    ports:
      - '3001:3001'
      - '3000:3000'
      - '5000:5000'
    volumes:
      - ./config.json:/config/config.json

volumes:
  postgres_data:
    name: github-agent-postgres-data
