name: Checks

on:
  push:
    branches:
      - '**'
    paths:
      - 'apps/**/src/**.ts'
      - 'apps/**/src/**.js'
      - 'packages/**/src/**.ts'
      - 'packages/**/src/**.js'
      - 'pnpm-lock.yaml'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-tests:
    name: Lint and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install environment
        uses: ./.github/actions/setup-env

      - name: Run ESLint
        run: pnpm lint

      - name: Run tests
        run: pnpm test:run
